version: 12 # НЕ МЕНЯТЬ
# список бустов
boosts: # it's list
  - name: donat-1 # имя (может быть любым)
    permission: 'auc.boost.donat1' # (пермишен по которому будет определяться наличие буста)
    external-slots: 2 # (дополнительные слоты)
    external-sell-time: '1d' # (дополнительное время продажи)
    # (ниже следующий буст)
  - name: unlimited-slots
    permission: 'bauc.unlimited.slots'
    external-slots: 999999
    external-sell-time: '0'

  - name: unlimited-sell-time
    permission: 'bauc.unlimited.sell-time'
    external-slots: 0
    external-sell-time: '10y'

lang: 'ru_ru' # Плагин подгружает имена предметов, полный список поддерживаемых языков https://github.com/InventivetalentDev/minecraft-assets/tree/1.16.5/assets/minecraft/lang
home-menu: 'home' # id меню которое будет открыто командой /ah
player-items-view-menu: 'playerItemsView'
default-slots: 10
logging: false # включить ли логирование сделок.
# Ограничение на размер предмета, если предмет весит больше то его не получится выставить на аукцион
item-max-size: 70000
# Плагин будет сжимать предмет если он весит больше чем {compress-if-more-than} байтов.
compress-if-more-than: 30000
# Если после сжатия предмет влазит в {item-max-size}, то тогда проверяется следующий лимит
# Нормальный размер предмета с большим количеством хексов менее 10к байтов.
# Для шалкеров это менее 100к байтов. Но это всё равно очень большие предметы.
maximum-uncompressed-item-size: 350000

allow-buy-count: true

# Время жизни офера по умолчанию. Для указания времени можно использовать: 1s1m1h1d1w1mo1y
default-offer-time: '2d'

offer-min-price: 10
offer-max-price: 100000000

economy: 'Vault' # Vault | PlayerPoints | BVault (https://github.com/By1337/BVault)
BVault-setting:
  current-bank: vault

remove-expired-items:
  enable: true # Удалять ли просроченные предметы?
  time: '2d' # Если да то через сколько

# здесь необходимо указать теги
black-list:
  - 'debug_stick'