boosts: # it's list
  - name: donat-1
    permission: 'auc.boost.donat1'
    external-slots: 2
    external-sell-time: '1d'
  - name: unlimited-slots
    permission: 'bauc.unlimited.slots'
    external-slots: 999999
    external-sell-time: '0'
  - name: unlimited-sell-time
    permission: 'bauc.unlimited.sell-time'
    external-slots: 0
    external-sell-time: '50y'

max-slots: 10

# Время жизни офера по умолчанию. Для указания времени можно использовать: 1s1m1h1d1w1mo1y
# Также можно изменить время жизни офера для определённого игрока с помощью команды: /ah offerTime <время>
default-offer-time: '2d'


# Когда продаваемый предмет один
selling-item-one:
  lore:
    - '&r '
    - '&#5AD9FB&n▌&r &fПродавец: &#5AD9FB{seller_name}'
    - '&#5AD9FB&n▌&r &fЦена: &#5AD9FB{price}'
    - '&#5AD9FB▌&r &fИстекает: &#5AD9FB{expires}'
    - '&r '
  left_click_commands:
    - '[BUY_ITEM_FULL] {id}'
  right_click_commands:
    - '[BUY_ITEM_FULL] {id}'


# Когда игрок owner предмета
take-item:
  lore:
    - '&r '
    - '&#5AD9FB&n▌&r &fПродавец: &#5AD9FB{seller_name}'
    - '&#5AD9FB&n▌&r &fЦена: &#5AD9FB{price}'
    - '&#5AD9FB&n▌&r &fИстекает: &#5AD9FB{expires}'
    - '&#5AD9FB▌&r &fПродажа по штучно: &#5AD9FB{sale_by_the_piece_format}'
    - '&r '
    - '&#5AD9FB▌&r &fЧтобы снять с продажи нажмите &#5AD9FBлкм'
  left_click_commands:
    - '[TAKE_ITEM] {id}'

# Когда продаваемый предмет не один и его можно купить поштучно
selling-item:
  lore:
    - '&r '
    - '&#5AD9FB&n▌&r &fПродавец: &#5AD9FB{seller_name}'
    - '&#5AD9FB&n▌&r &fЦена: &#5AD9FB{price}'
    - '&#5AD9FB&n▌&r &fЦена за штуку &#5AD9FB{price_for_one}'
    - '&#5AD9FB▌&r &fИстекает: &#5AD9FB{expires}'
    - '&r '
    - '&#5AD9FB&n▌&r &fЧтобы купить всё нажмите &#5AD9FBлкм'
    - '&#5AD9FB▌&r &fДля покупки поштучно нажмите &#5AD9FBпкм'
  left_click_commands:
    - '[BUY_ITEM_FULL] {id}'
  right_click_commands:
    - '[BUY_ITEM_AMOUNT] {id}'

# Когда продаваемый предмет не один и его нельзя купить поштучно
selling-item-only-full:
  lore:
    - '&r '
    - '&#5AD9FB&n▌&r &fПродавец: &#5AD9FB{seller_name}'
    - '&#5AD9FB&n▌&r &fЦена: &#5AD9FB{price}'
    - '&#5AD9FB▌&r &fИстекает: &#5AD9FB{expires}'
    - '&r '
    - '&#5AD9FB&n▌&r &fПродавец &#ABF0FAограничил &fуказание'
    - '&#5AD9FB&n▌&r &fколичества товара при покупке.'
    - '&#5AD9FB▌&r &#ABF0FAКупить можно только полностью'
  left_click_commands:
    - '[BUY_ITEM_FULL] {id}'
  right_click_commands:
    - '[BUY_ITEM_FULL] {id}'